Various improvements
EmbeddedEnterprises/cmake-ts pull request #12
Opened 2021-04-19 07:23 UTC by aminya

2021-04-19 08:55 UTC, martin31821 requested changes
Looks good besides the two points I annotated to main.ts

2021-04-19 08:55 UTC, martin31821 commented on src/main.ts
> -  const nativeonly = process.argv.some(arg => arg === 'nativeonly');
why change those?

2021-04-19 08:55 UTC, martin31821 commented on src/main.ts
> +    if (configs.configurations === undefined) {
maybe this check should be moved to the top of the file?
i.e.exit immediately, if no build config could be found?

2021-04-19 08:55 UTC, martin31821 commented on src/main.ts
> +  console.log('running in', packageDir, 'command', /* command */ argv);
leftover /* command */ can be removed.

2021-04-19 08:55 UTC, martin31821 commented on src/main.ts
> +  if (configs.configurations === undefined) {
duplicate from above?

2021-04-19 09:06 UTC, aminya commented
@martin31821 Sorry I was still making the code pretty. 😄 I moved the whole defaulting process into separate functions to make the `main` function clean and understandable.

Could you re-review?

2021-04-19 09:10 UTC, aminya commented on src/main.ts
> +    if (configs.configurations === undefined) {
Yes, I think we can handle this without error by using `defaultBuildConfigurations`. I believe that the tool should work even with minimal configurations.

2021-04-19 09:10 UTC, aminya commented on src/main.ts
> -  const nativeonly = process.argv.some(arg => arg === 'nativeonly');
Yes, we can use `includes`. I don't think the performance is critical here as the array is small anyway.

2021-04-19 09:14 UTC, aminya commented on src/main.ts
> -  const nativeonly = process.argv.some(arg => arg === 'nativeonly');
Fixed in 
https://github.com/EmbeddedEnterprises/cmake-ts/pull/12/commits/056eea42d04b54b84107844cb97e0fb2b53ed9db

2021-04-19 09:15 UTC, aminya commented on src/main.ts
> +  if (configs.configurations === undefined) {
Fixed

2021-04-19 09:15 UTC, aminya commented on src/main.ts
> +  console.log('running in', packageDir, 'command', /* command */ argv);
Fixed
https://github.com/EmbeddedEnterprises/cmake-ts/pull/12/commits/40b1b33ce71e3e43220bd5d5dcebff24e8a8683d

2021-04-20 08:18 UTC, martin31821 reviewed
LGTM besides the two TODOs.

2021-04-20 08:18 UTC, martin31821 commented on src/lib.ts
> +  // TODO move the code related to customNANPackageName
Do you want to move those or is that something to consider later?

2021-04-20 08:18 UTC, martin31821 commented on src/main.ts
> +    // TODO getting the path from the CLI
Fix in this PR or later?

2021-04-20 08:37 UTC, aminya commented on src/lib.ts
> +  // TODO move the code related to customNANPackageName
Probably later. Maybe, we decide that it is not actually needed.

2021-04-20 08:37 UTC, aminya commented on src/main.ts
> +    // TODO getting the path from the CLI
Yes. This can be done later.

2021-04-20 08:42 UTC, martin31821 approved these changes

2021-04-20 08:42 UTC, merged