Fix vs generator finder
EmbeddedEnterprises/cmake-ts pull request #30
Opened 2024-11-22 11:11 UTC by diefbell-grabcad

If a newer version of Visual Studio build tools (>= 2019) is installed then the automatic build tools finder fails because `cmake -G` outputs:
```
Generators
* Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
```

and the function `GET_CMAKE_VS_GENERATOR` doesn't recognise them because it expects the ` [arch]` suffix. 

This fixes:
    - Above issue;
    - Issue where one of the build tools is prefixed by `* ` (I think that means it's the system default or something? Idk;)
    - For the build tools that don't end with ` [arch]`, it appends `-A arch` to the generator string in the argumentBuilder (kinda janky).

2024-11-26 17:43 UTC, aminya requested changes

2024-11-26 17:43 UTC, aminya commented on package.json
> +  "version": "0.4.0",
Please keep the version as is. We can publish it as a patch

2024-11-27 11:02 UTC, diefbell-grabcad commented on package.json
> +  "version": "0.4.0",
So bump patch version? Or just leave as is?

2024-11-27 16:48 UTC, aminya commented on package.json
> +  "version": "0.4.0",
Leave as is. I'll handle the version bunp

2024-11-27 23:20 UTC, diefbell-grabcad commented on package.json
> +  "version": "0.4.0",
Done

2024-11-27 23:22 UTC, diefbell-grabcad commented
> I had rebased this into a single commit. Any reason to undo that? Could you rebase and squash the changes?

I have no idea how that happened. I can try just creating a new branch. I think because my branch was off your fork originally.

2024-11-28 00:26 UTC, aminya commented
Sounds good. Here's the branch I rebased:
https://github.com/EmbeddedEnterprises/cmake-ts/tree/vs-cmake-generator

2024-11-28 09:15 UTC, closed without merging

2024-11-28 10:57 UTC, diefbell-grabcad commented
Created https://github.com/EmbeddedEnterprises/cmake-ts/pull/32 without mess un-squash